### ISSUE TITLE
Doesnt run on windows

### ISSUE THREAD

**Issue by alfredoperez** [MichaelSolati/ng-popular-movies-pwa#1]
Hey, excellent application and blog post! I cannot run the ngu commands on a windows. any suggestions?

**Comment by MichaelSolati** [comment]
The [commands should work](https://github.com/alxhub/io17#the-ng-pwa-tools), but you may need to manually run them instead of having the `npm scripts` run everything...

But try this (based off of the io17 repo).

```
#!/bin/bash
PATH=$PATH:$(npm bin)
set -x

# Production build
ng build --prod

./node_modules/.bin/ngu-app-shell --module src/app/app.module.ts --out dist/index.html

./node_modules/.bin/ngu-sw-manifest --module src/app/app.module.ts --out dist/ngsw-manifest.json

# Serve
cd dist
http-server
```

**Comment by alfredoperez** [comment]
i get an error saying :

 ENOENT: no such file or directory, open 'C:\training\ng-popular-movies-pwa\app.component.html' 

i think the problem is in the file loader from \node_modules\ng-pwa-tools\lib\common\ng.js

the url of the file looks like C:app.component.html

**Comment by MichaelSolati** [comment]
It seems from my testing that prefixing the `ngu-app-shell` and `ngu-sw-manifest` with `node` should get the `ng-pwa-tools` to work ([see here](https://github.com/alxhub/io17/issues/9#issuecomment-303358083)). However this seems to be more of an issue with how the `ng-pwa-tools` handles Windows rather than this code base itself.

I'll be closing the issue, and think moving forward issues of this nature should be opened on the [`ng-pwa-tools` repo](https://github.com/alxhub/io17/issues).
